name: Python checks
on:
    push:
    pull_request:
        branches:
            - master
jobs:
    check_python:
        runs-on: ubuntu-latest
        steps:
            - name: Set up Git repository
              uses: actions/checkout@v2
            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                python-version: '3.x'
            - name: Install poetry
              run: pip install poetry
            - name: Install poetry dependencies
              run: poetry install
            - name: Run unit tests
              run: make test
            - name: Run coverage test
              run: make coverage
            - name: Run lint
              run: make lint
