name: Lint, spell & grammar check LaTeX document
on:
    push:
    pull_request:
        branches:
            - master
jobs:
    check_latex:
        runs-on: ubuntu-latest
        env:
            IgnoreArgs: --ignore sh:seclen,sh:stacked --remove-macros tableofcontents,listoffigures,listoftables,begin,centeroffset,oddsidemargin,evensidemargin,centering,bfseries,end,cleardoublepage
        steps:
            - name: Set up Git repository
              uses: actions/checkout@v2
            - name: Check Spanish text
              uses: ChiefGokhlayeh/textidote-action@v5
              id: check_es
              with:
                  root_file: doc/proyecto.tex
                  report_file: report_es.html
                  args: --check es --remove otherlanguage $IgnoreArgs
            - name: Check English text
              uses: ChiefGokhlayeh/textidote-action@v5
              id: check_en
              with:
                  root_file: doc/prefacios/english_abstract.tex
                  report_file: report_en.html
                  args: --check en --read-all $IgnoreArgs
            - name: Upload TeXtidote report
              uses: actions/upload-artifact@v3
              with:
                  name: textidote_report
                  path: report_*.html
            - name: Throw error if warnings exist
              if: ${{ steps.check_es.outputs.num_warnings != 0 || steps.check_en.outputs.num_warnings != 0}}
              run: 'echo "::error file=doc/proyecto.tex::num_warnings_es: ${{ steps.check_es.outputs.num_warnings }}, num_warnings_en: ${{ steps.check_en.outputs.num_warnings }}"; exit 1;'
